version: '3'
services:
    php-apache:
        build:
            context: .
        ports:
            -  80:80
        volumes:
            - .:/var/www/html
        links:
            - 'mysql8'
    mysql8:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
      ports:
        - 3306:3306
      expose:
        - 3306
      volumes:
        - mysql8:/var/lib/mysql
volumes:
    mysql8: